# Generated by Django 5.2.8 on 2026-01-04 18:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('points_required', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('times_redeemed', models.IntegerField(default=0)),
                ('visits_required', models.IntegerField(blank=True, help_text='Number of visits required (leave empty for points-only rewards)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('hair', 'Hair Services'), ('spa', 'Spa & Massage'), ('nails', 'Nail Services'), ('facial', 'Facial & Beauty'), ('massage', 'Massage Services'), ('makeup', 'Makeup Services'), ('body', 'Body Treatments'), ('packages', 'Packages'), ('other', 'Other Services')], default='hair', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(default=30, help_text='Duration in minutes')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interval', models.CharField(default='month', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(help_text='Comma-separated list of features')),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('business_type', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('primary_color', models.CharField(default='#D97706', max_length=7)),
                ('auto_campaign_we_miss_you', models.BooleanField(default=False)),
                ('we_miss_you_discount_pct', models.IntegerField(default=10)),
                ('we_miss_you_days', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Business email for reply-to', max_length=254, null=True)),
                ('email_from_name', models.CharField(default='ClientPulse', max_length=255)),
                ('notify_on_payment', models.BooleanField(default=True)),
                ('notify_on_customer_signup', models.BooleanField(default=True)),
                ('email_cust_booking_received', models.BooleanField(default=True, help_text='Booking received (pending)')),
                ('email_cust_booking_approved', models.BooleanField(default=True, help_text='Booking approved')),
                ('email_cust_booking_rejected', models.BooleanField(default=True, help_text='Booking rejected')),
                ('email_cust_booking_rescheduled', models.BooleanField(default=True, help_text='Booking rescheduled')),
                ('email_cust_booking_cancelled', models.BooleanField(default=True, help_text='Booking cancelled by business')),
                ('email_cust_booking_reminder', models.BooleanField(default=True, help_text='Booking reminder (24h / 2h)')),
                ('email_cust_booking_noshow', models.BooleanField(default=False, help_text='Booking no-show notice')),
                ('email_cust_booking_completed', models.BooleanField(default=False, help_text='Booking completed / thank you')),
                ('email_tenant_new_booking', models.BooleanField(default=True, help_text='New booking alert')),
                ('email_tenant_booking_cancelled', models.BooleanField(default=True, help_text='Booking cancellation')),
                ('email_tenant_reschedule_request', models.BooleanField(default=True, help_text='Reschedule request')),
                ('business_hours', models.JSONField(blank=True, default=dict, help_text="e.g. {'monday': {'open': '09:00', 'close': '18:00'}, ...}")),
                ('onboarding_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('points', models.IntegerField(default=0)),
                ('last_purchase', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit_count', models.IntegerField(default=0, help_text='Total number of visits')),
                ('last_we_miss_you_sent', models.DateField(blank=True, null=True)),
                ('service_notes', models.TextField(blank=True, help_text='Style preferences, allergies, special notes')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customer_photos/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
                ('favorite_services', models.ManyToManyField(blank=True, related_name='favorited_by', to='clientapp.service')),
            ],
        ),
        migrations.CreateModel(
            name='CustomersDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Customers Dashboard',
                'verbose_name_plural': 'Customers Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clientapp.customer',),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('staff', 'Staff')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clientapp.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyNotification',
            fields=[
            ],
            options={
                'verbose_name': 'My Notification',
                'verbose_name_plural': 'My Notifications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clientapp.notification',),
        ),
        migrations.CreateModel(
            name='RewardsDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Rewards Dashboard',
                'verbose_name_plural': 'Rewards Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clientapp.reward',),
        ),
        migrations.AddField(
            model_name='reward',
            name='applicable_services',
            field=models.ManyToManyField(blank=True, related_name='rewards', to='clientapp.service'),
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('specialty', models.CharField(blank=True, help_text='e.g. Senior Barber, Hair Colorist', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clientapp.staffmember'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_customers', to='clientapp.staffmember'),
        ),
        migrations.AddField(
            model_name='service',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.tenant'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='clientapp.customer')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='reward',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.tenant'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(default='M-Pesa', max_length=50)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientapp.subscriptionplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.tenant'),
        ),
        migrations.CreateModel(
            name='CustomerReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_claimed', models.DateTimeField(auto_now_add=True)),
                ('date_redeemed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Redemption'), ('redeemed', 'Redeemed/Used'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_rewards', to='clientapp.customer')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.reward')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.tenant'),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('no_show', 'No-Show')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='clientapp.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.service')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='clientapp.staffmember')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clientapp.tenant',),
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('next_billing_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientapp.subscriptionplan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='clientapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='admin_photos/')),
                ('role', models.CharField(choices=[('platform_admin', 'Platform Admin'), ('tenant_admin', 'Tenant Admin'), ('staff', 'Staff'), ('customer', 'Customer')], default='tenant_admin', max_length=20)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partially Paid')], default='paid', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('review_request_sent', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clientapp.customer')),
                ('services', models.ManyToManyField(to='clientapp.service')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='clientapp.staffmember')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('reviewer_type', models.CharField(choices=[('customer', 'Customer'), ('business_owner', 'Business Owner')], default='customer', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clientapp.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.tenant')),
                ('visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='clientapp.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clientapp.visit',),
        ),
    ]
