# Generated by Django 5.2.8 on 2026-01-07 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='clientapp.booking'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='clientapp.visit'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
