# Generated by Django 5.2.8 on 2026-01-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0003_paymenttransaction_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='email_cust_booking_completed',
            field=models.BooleanField(default=True, help_text='Booking completed / thank you'),
        ),
    ]
