# Generated by Django 5.2.8 on 2025-12-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0003_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('points_required', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('times_redeemed', models.IntegerField(default=0)),
            ],
        ),
    ]
