# Generated by Django 5.2.8 on 2026-01-07 21:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_alter_tenant_email_cust_booking_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of service revenue earned by staff (0-100)', max_digits=5),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Retail Price', max_digits=10)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Cost Price for profit calc', max_digits=10, null=True)),
                ('current_stock', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_quantity', models.IntegerField(help_text='Positive for addition, negative for deduction')),
                ('reason', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.tenant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='clientapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProductConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, help_text='Amount consumed per service')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_consumption', to='clientapp.service')),
            ],
        ),
    ]
