# Generated by Django 5.2.8 on 2026-01-08 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0006_expense_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_on_behalf', to='clientapp.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_minor',
            field=models.BooleanField(default=False, help_text='Flag for children/minors'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_registered',
            field=models.BooleanField(default=False, help_text='True if they have a system user account'),
        ),
        migrations.AddField(
            model_name='customer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='clientapp.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='parent_contact',
            field=models.CharField(blank=True, help_text='Parent contact info for minors', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
