# Generated by Django 5.2.8 on 2025-12-14 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0006_customer_location_customer_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('hair', 'Hair Services'), ('spa', 'Spa & Massage'), ('nails', 'Nail Services'), ('facial', 'Facial & Beauty'), ('other', 'Other Services')], default='hair', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(default=30, help_text='Duration in minutes')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='service_notes',
            field=models.TextField(blank=True, help_text='Style preferences, allergies, special notes'),
        ),
        migrations.AddField(
            model_name='customer',
            name='visit_count',
            field=models.IntegerField(default=0, help_text='Total number of visits'),
        ),
        migrations.AddField(
            model_name='reward',
            name='visits_required',
            field=models.IntegerField(blank=True, help_text='Number of visits required (leave empty for points-only rewards)', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='favorite_services',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='clientapp.service'),
        ),
        migrations.AddField(
            model_name='reward',
            name='applicable_services',
            field=models.ManyToManyField(blank=True, related_name='rewards', to='clientapp.service'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_customers', to='clientapp.staffmember'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partially Paid')], default='paid', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clientapp.customer')),
                ('services', models.ManyToManyField(to='clientapp.service')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='clientapp.staffmember')),
            ],
        ),
    ]
