# Generated by Django 5.2.8 on 2026-01-08 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0007_booking_booked_by_customer_customer_is_minor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_record', to='clientapp.booking'),
        ),
    ]
