# Generated by Django 5.2.8 on 2026-01-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0008_visit_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional staff profile photo', null=True, upload_to='staff_photos/'),
        ),
    ]
