# Generated by Django 5.2.8 on 2025-12-15 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0008_booking_customerreward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerWebsite',
        ),
    ]
