# Generated by Django 5.2.8 on 2026-01-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0011_customer_referral_code_customer_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_24h_sent',
            field=models.BooleanField(default=False, help_text='24-hour reminder'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Short-term reminder (30m)'),
        ),
    ]
