# Generated by Django 5.2.8 on 2025-12-30 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0017_subscriptionplan_tenantsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(default='M-Pesa', max_length=50)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientapp.subscriptionplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.tenant')),
            ],
        ),
    ]
