# Generated by Django 5.2.8 on 2025-12-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0018_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
