# Generated by Django 5.2.8 on 2025-12-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0019_tenant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyNotification',
            fields=[
            ],
            options={
                'verbose_name': 'My Notification',
                'verbose_name_plural': 'My Notifications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clientapp.notification',),
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clientapp.visit',),
        ),
        migrations.CreateModel(
            name='RewardsDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Rewards Dashboard',
                'verbose_name_plural': 'Rewards Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clientapp.reward',),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clientapp.tenant',),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
