# Generated by Django 5.2.8 on 2025-12-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0020_mynotification_reports_rewardsdashboard_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, help_text='Business email for reply-to', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_from_name',
            field=models.CharField(default='ClientPulse', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notify_on_booking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notify_on_customer_signup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notify_on_payment',
            field=models.BooleanField(default=True),
        ),
    ]
