# Generated by Django 5.2.8 on 2025-12-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0021_tenant_email_tenant_email_from_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='notify_on_booking',
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_cust_booking_approved',
            field=models.BooleanField(default=True, help_text='Booking approved'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_cust_booking_cancelled',
            field=models.BooleanField(default=True, help_text='Booking cancelled by business'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_cust_booking_completed',
            field=models.BooleanField(default=False, help_text='Booking completed / thank you'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_cust_booking_noshow',
            field=models.BooleanField(default=False, help_text='Booking no-show notice'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_cust_booking_received',
            field=models.BooleanField(default=True, help_text='Booking received (pending)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_cust_booking_rejected',
            field=models.BooleanField(default=True, help_text='Booking rejected'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_cust_booking_reminder',
            field=models.BooleanField(default=True, help_text='Booking reminder (24h / 2h)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_cust_booking_rescheduled',
            field=models.BooleanField(default=True, help_text='Booking rescheduled'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_tenant_booking_cancelled',
            field=models.BooleanField(default=True, help_text='Booking cancellation'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_tenant_new_booking',
            field=models.BooleanField(default=True, help_text='New booking alert'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_tenant_reschedule_request',
            field=models.BooleanField(default=True, help_text='Reschedule request'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('no_show', 'No-Show')], default='pending', max_length=20),
        ),
    ]
