# Generated by Django 5.2.8 on 2026-01-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0022_remove_tenant_notify_on_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('hair', 'Hair Services'), ('spa', 'Spa & Massage'), ('nails', 'Nail Services'), ('facial', 'Facial & Beauty'), ('massage', 'Massage Services'), ('makeup', 'Makeup Services'), ('body', 'Body Treatments'), ('packages', 'Packages'), ('other', 'Other Services')], default='hair', max_length=50),
        ),
    ]
