# Generated by Django 5.2.8 on 2026-01-03 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0023_alter_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Customers Dashboard',
                'verbose_name_plural': 'Customers Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clientapp.customer',),
        ),
        migrations.AddField(
            model_name='booking',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'monday': {'open': '09:00', 'close': '18:00'}, ...}"),
        ),
        migrations.AddField(
            model_name='tenant',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
