# Generated by Django 5.2.8 on 2026-01-03 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0026_alter_booking_uuid_alter_customer_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='specialty',
            field=models.CharField(blank=True, help_text='e.g. Senior Barber, Hair Colorist', max_length=200),
        ),
        migrations.AddField(
            model_name='visit',
            name='review_request_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clientapp.customer')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.tenant')),
                ('visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='clientapp.visit')),
            ],
        ),
    ]
